"""ingredient modify

Revision ID: 5d518b56b9e8
Revises: cdd91abe1996
Create Date: 2022-03-18 09:06:39.749641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d518b56b9e8'
down_revision = 'cdd91abe1996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RecipeIngredient')
    op.drop_table('recipe_ingredients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name='recipe_ingredients_ingredient_id_fkey'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='recipe_ingredients_recipe_id_fkey'),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id', name='recipe_ingredients_pkey')
    )
    op.create_table('RecipeIngredient',
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ingredient_Id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ingredient_Id'], ['ingredients.id'], name='RecipeIngredient_ingredient_Id_fkey'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='RecipeIngredient_recipe_id_fkey')
    )
    # ### end Alembic commands ###
