"""change column rate to float

Revision ID: a481e61a747e
Revises: eff45b3a5058
Create Date: 2022-03-21 10:36:30.566356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a481e61a747e'
down_revision = 'eff45b3a5058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
