"""ingredient relationship

Revision ID: cdd91abe1996
Revises: 6e4bb07505e5
Create Date: 2022-03-17 08:45:47.684175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd91abe1996'
down_revision = '6e4bb07505e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RecipeIngredient',
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_Id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_Id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RecipeIngredient')
    # ### end Alembic commands ###
