"""add tabel rating

Revision ID: eff45b3a5058
Revises: 5d518b56b9e8
Create Date: 2022-03-18 12:32:55.500599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff45b3a5058'
down_revision = '5d518b56b9e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocena')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocena',
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='ocena_owner_id_fkey'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='ocena_recipe_id_fkey'),
    sa.PrimaryKeyConstraint('recipe_id', 'owner_id', name='ocena_pkey')
    )
    # ### end Alembic commands ###
